on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator:
    runs-on: self-hosted
    name: Evaluator
    steps:
      - name: Fetch project repository
        uses: actions/checkout@v2

      - name: Fetch ESLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/eslint-linter-action
          ref: v3.4
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/eslint-evaluator

      - name: Fetch StyleLint evaluator
        uses: actions/checkout@v2
        with:
          repository: betrybe/stylelint-linter-action
          ref: v2.1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/stylelint-evaluator

      - name: Fetch Blocked Files Checkout action
        uses: actions/checkout@v2
        with:
          repository: betrybe/blocked-files-checkout-action
          ref: v2
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/blocked-files-checkout
          
      - name: Fetch Vitest2
        uses: actions/checkout@v3
        with:
          repository: betrybe/vitest-evaluator-action
          ref: v1
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/vitest-evaluator

      - name: Fetch Requirements Evaluation Table Action
        uses: actions/checkout@v2
        with:
          repository: betrybe/requirements-evaluation-table-action
          ref: v1.0
          token: ${{ secrets.GIT_HUB_PAT }}
          path: .github/actions/requirements-evaluation-table-action

      - name: Setup NodeJS
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '16'

      - name: Restore protected files
        uses: ./.github/actions/blocked-files-checkout
        with:
          restore_branch: 'master'

      - name: Run ESLint evaluator
        uses: ./.github/actions/eslint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Run StyleLint evaluator
        uses: ./.github/actions/stylelint-evaluator
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}

      - name: Run Vitest evaluation
        id: evaluator
        uses: ./.github/actions/vitest-evaluator
        with:
          pr_author_username: ${{ github.event.pull_request.user.login }}

      - name: Run Requirements Evaluation Table Action
        uses: ./.github/actions/requirements-evaluation-table-action
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          pr_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
